spring:
    application:
        name: discovery
#### security
    security: 
        basic:
            enabled: true
            path=/**
        user:
            name: system
            password: systemPass
            role: ADMIN
        sessions: always
server:
    port: 8761

#### cloud
eureka:
    instance:
        hostname: localhost
    client: 
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://system:systemPass@localhost:8761/eureka}
        registerWithEureka: false
        fetchRegistry: false

